### ISSUE TITLE
Upgrade to Capacitor 7

### ISSUE THREAD

**Issue by jimcase** [evva-sfw/capacitor-secure-storage-plugin#33]
This plugin needs to be updated for compatibility with Capacitor 7. Please update dependencies and ensure it works correctly with the latest Capacitor version.

**Comment by 0x7061** [comment]
Resolved in release `4.0.0`.

**Comment by Nirzol** [comment]
I think you forgot to change this : package.json
    "peerDependencies": {
        "@capacitor/core": "^6.1.2"
    },
